CREATE TABLE IF NOT EXISTS numbers
(
    id                int GENERATED BY DEFAULT AS IDENTITY,
    series            varchar(3) NOT NULL,
    registration_code int        NOT NULL CHECK (registration_code >= 1 AND registration_code <= 999),
    region_code       int        NOT NULL,
    country           varchar(3) NOT NULL,
    PRIMARY KEY (series, registration_code, region_code, country)
);